### ISSUE TITLE
how you introduce a constant  term in SSFM

### ISSUE THREAD

**Issue by yumtong** [tony-ko/LLEF#2]
Hello,I can't understand the code in the matlab ,
Can you tell me why " const_add = const_term.*(exp_prop - 1)./prop;"
    
% this can seem incoherent, but this is how you introduce a constant
    % term in SSFM
   
Thank you very much ~~~

**Comment by tony-ko** [comment]
I have already answered a similar question on ResearchGate, I will reproduce the answer here.

To treat a constant (driving) term in LLE with a split-step method you simply include it in the expression for the linear part of dE/dt, and then integrate it with respect to time to obtain a solution after a time step.

Say, you have linear part written as

dE/dt = A + K*E, where K can include your -(1 + i*theta) term accounting for losses and detuning as well as -i*beta*d^2/dtau^2 term for the dispersion (as well as higher-order dispersion terms), and A can be the pump parameter or other constant terms (which are not multiplied by E in the original equation).

Before treating a linear part with FFT, you need to find first its explicit solution after a time step h. And this is an important step. You do not just do an FFT and IFFT of the linear part. You need to propagate it first to the time step h and then treat the dispersion. Eventually, you will end up with the following relation:
E(t+h, tau) = A*(exp(K*h)-1)/K + exp(K*h)*E(t, tau)

How to obtain this exact solution?

Let us start without a driving term. What we come up with is a rather simple differential equation (note: of course, it is a partial differential equation, we consider the second dimension fixed here):

dE/dt = K*E,

and its solution is

E(t,tau) = E(t0,tau)*exp(K*(t-t0)),

and E(t0,tau) is some known value at the time t0.

So, for the time t+h you end up with a well-known relation:
E(t + h,tau) = E(t,tau)*exp(K*h).

It is just your regular propagation in a dispersive medium in the absence of the constant driving field, and this what you further treat with FFT.

I recalled all this just to remind how the exp(K*h) term appears in the equation. Notice that it is obtained not in a general form but for a specific initial condition.

Let us now return to the case of interest:
dE/dt = A + K*E.

This little guy (driving term) introduces all the fun to a solution after a time step h, all because of the initial condition.

First of all, this is a separable equation, so what we need to do is:
dE/(A+K*E) = dt

Then we integrate both sides:
log(A + K*E)/K = t + C0,
or
A + K*E = exp(K*t)*C1, where C1 = exp(K*C0),
E = exp(K*t)*C1/K - A/K.

This form almost assumes to use it in FFT, but it is not ready yet since the integration constant C1 is not defined.

Let us suppose we know some initial condition E(t0) = E0, then:
E0 = exp(K*t0)*C1/K - A/K,
from which:
C1 = (A + E0*K)*exp(-K*t0).

Substuting this constant to the solution for E:
E = exp(K*t)*(A + E0*K)*exp(-K*t0)/K - A/K.

After some algebra:
E(t) = A*(exp(K*(t-t0))-1)/K + exp(K*(t-t0))*E(t0)

Considering subsequent replacement t -> t + h, and t0 -> t, we get that form in question:
E(t + h) = A*(exp(K*h)-1)/K + exp(K*h)*E(t)

Then you can treat it with FFT, and obtain:
E(t+h, tau) = IFFT[FA*(exp(FK*h)-1)/FK + exp(FK*h) * FFT(E(t, tau))],
where FA = FFT(A), so you will discretize A in tau and take FFT of it, FK is calculated in the same manner. Basically, you replace -i*beta*d^2/dtau^2 by -i*omega^2, where omega is your Fourier wavenumbers.

In the code
const_add is FA*(exp(FK*h)-1)/FK 
const_term is FA
exp_prop is exp(FK*h)
prop is FK

**Comment by yumtong** [comment]
Thank you very much for your reply, I will read it carefully.
